### ISSUE TITLE
Example interaction with telegram chatbot

### ISSUE THREAD

**Issue by lifelongeek** [MIPTDeepLearningLab/ConvAI-baseline#4]
After successfully executing './bot.sh start', I found my telegram chatbot send me some paragraph.
I was trying to ask question to the bot, but it does not respond at all.
Could you provide some examples how I can interact with the bot in telegram?

Below is the example of current message platform.

![image](https://user-images.githubusercontent.com/10232337/27775279-9c6849f6-5fdb-11e7-8edb-c714fcfa9570.png)

**Comment by madrugado** [comment]
Actually, that should be enough, I propose to restart it. It could take some time to start all the services needed.

Also the most time consuming service is question generation, you could go into ```./guestion_generation``` folder and run ```./setup```, it comes with test included, so you'll see the text and generated questions, if it's ok.

**Comment by lifelongeek** [comment]
Thanks for the comment +1:
